//@version=5
indicator("B002 Moving Average crossover", "MAcross", true)
src = input.source(close, "Source")
fast_len = input.int(50, "Fast Length")
slow_len = input.int(100, "Slow Length")

fast_sma = ta.sma(src, fast_len)
slow_sma = ta.sma(src, slow_len)
plot(fast_sma, "Fast SMA", color.green, 1)
plot(slow_sma, "Slow SMA", color.red, 2)

longCondition = ta.crossover(fast_sma, slow_sma)
plotshape(longCondition, "Buy", shape.labelup, location.belowbar, color.green, text = "Buy", 
 textcolor = color.white)