//@version=5
indicator("A038 Custom Methods change box color", overlay = true)

type Gap
    bool isActive
    box channel

var allBox = array.new<Gap>()

method Close(Gap item, index) => 
    // if (high >= item.channel.get_top() or low <= item.channel.get_bottom())  // if i add >= or <= sign its not working ?
    if (high > item.channel.get_top() or low < item.channel.get_bottom())
        item.channel.set_right(bar_index)
        allBox.remove(index)
        int(na)
    else
        item.channel.set_right(bar_index)
        int(na)

method decorate(box bCol) =>
    bCol.set_bgcolor(high > bCol.get_top() ? #00FF00 : low < bCol.get_bottom() ? #FF0000 : #FFFF00)

if session.isfirstbar
    BOX = box.new(bar_index, high, bar_index+5, low)
    // BOX.decorate() // This is gugli from Manish Bhai as color would always be yellow as we are checking on first candle
    allBox.push(Gap.new(isActive = true, channel = BOX))
for [index,gap] in allBox
    gap.Close(index)
    gap.channel.decorate()
