print("Welcome to the tip calculator.")
total_bill = float(input("What was the total bill? $"))
people = int(input("How many people to split the bill? "))
tip = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
each_person = round((total_bill * (1+tip/100))/people, 2)
# print("Each person should pay: $" + str(each_person))
print(f"Each person should pay: ${each_person:.2f}")